GET http://localhost:3000/todos/?status=TO%20DO
###
GET http://localhost:3000/todos/?priority=MEDIUM
###
GET http://localhost:3000/todos/?status=TO%20DO&priority=MEDIUM
###
GET http://localhost:3000/todos/?search_q=PYTHON
###
GET http://localhost:3000/todos/9/
###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
    "status": "IN PROGRESS"
}
###
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
    "priority": "HIGH"
}
###
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
    "todo": "LEARN BOOTSTRAP"
}
###
DELETE http://localhost:3000/todos/10/